# Usage with docker-compose
#   (Build) docker-compose build
#   (Run) docker-compose up 

version: '3.8'

services:
  jenkins:
    build:
      context: .
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./conf:/var/jenkins_config
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_config/jenkins.yaml
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin

volumes:
  jenkins_home: